name: Release
on:
  push:
    branches:
      - '**'
    tags:
      - '*'

env:
  JAVA_DIST: 'temurin'
  JAVA_VERSION: 26

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    # only on tag pushes, or if the commit message asks for a snapshot deploy
    if: startsWith(github.ref, 'refs/tags/') || contains(github.event.head_commit.message, '[deploy]')
    permissions:
      contents: read # Required for checkout
      id-token: write # Required for the attestations step
      attestations: write # Required for the attestations step
      artifact-metadata: write # Required for the attestations step
    outputs:
      sha256: ${{ steps.checksums.outputs.sha256 }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
      - name: Ensure to use tagged version
        if: startsWith(github.ref, 'refs/tags/')
        run: ./mvnw versions:set --file ./pom.xml -DnewVersion=${GITHUB_REF##*/}
      - name: Build and Test
        run: >
          ./mvnw -B verify --no-transfer-progress
      - name: Calculate Checksums
        id: checksums
        run: |
          {
            echo 'sha256<<EOF'
            shasum -a256 target/*.jar
            echo EOF
          } >> $GITHUB_OUTPUT
      - name: Attest
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/attest@a1948c3f048ba23858d222213b7c278aabede763 # v4.1.1
        with:
          subject-path: |
            target/*.jar
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: artifacts
          path: target/*.jar

  deploy-central:
    name: Deploy to Maven Central
    runs-on: ubuntu-latest
    permissions:
      id-token: write # OIDC token for sigstore signing
      contents: read # Required for sigstore signing
    needs: [build]
    if: github.repository_owner == 'cryptomator'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_PASSWORD
      - name: Enforce to use tagged version
        if: startsWith(github.ref, 'refs/tags/')
        run: ./mvnw versions:set -B -DnewVersion="${GITHUB_REF##*/}"
      - name: Verify project version is -SNAPSHOT
        if: startsWith(github.ref, 'refs/tags/') == false
        run: |
          PROJECT_VERSION=$(./mvnw help:evaluate "-Dexpression=project.version" -q -DforceStdout)
          test "${PROJECT_VERSION: -9}" = "-SNAPSHOT"
      - name: Deploy to Maven Central
        run: ./mvnw deploy -B -Psign,deploy-central --no-transfer-progress
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.RELEASES_GPG_PASSPHRASE }}
          MAVEN_GPG_KEY: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          MAVEN_GPG_KEY_FINGERPRINT: ${{ vars.RELEASES_GPG_KEY_FINGERPRINT }}

  deploy-github:
    name: Deploy to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write # Required for the deploy to GitHub Packages step
      id-token: write # OIDC token for sigstore signing
      contents: read # Required for sigstore signing
    needs: [build]
    if: github.repository_owner == 'cryptomator'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
      - name: Enforce to use tagged version
        if: startsWith(github.ref, 'refs/tags/')
        run: ./mvnw versions:set -B -DnewVersion="${GITHUB_REF##*/}"
      - name: Verify project version is -SNAPSHOT
        if: startsWith(github.ref, 'refs/tags/') == false
        run: |
          PROJECT_VERSION=$(./mvnw help:evaluate "-Dexpression=project.version" -q -DforceStdout)
          test "${PROJECT_VERSION: -9}" = "-SNAPSHOT"
      - name: Deploy to GitHub Packages
        run: ./mvnw deploy -B -DskipTests -Psign,deploy-github --no-transfer-progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.RELEASES_GPG_PASSPHRASE }}
          MAVEN_GPG_KEY: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          MAVEN_GPG_KEY_FINGERPRINT: ${{ vars.RELEASES_GPG_KEY_FINGERPRINT }}

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for the release step
    needs: [build, deploy-central, deploy-github]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        with:
          prerelease: true
          token: ${{ secrets.CRYPTOBOT_RELEASE_TOKEN }}
          generate_release_notes: true
          body: |-
            ### Maven Coordinates
            ```xml
              <dependency>
                <groupId>org.cryptomator</groupId>
                <artifactId>jackrabbit-webdav-jakarta</artifactId>
                <version>${{ github.ref_name }}</version>
              </dependency>
            ```

            ### Artifact Checksums
            ```txt
            ${{ needs.build.outputs.sha256 }}
            ```
